# Generated by Django 5.0.6 on 2024-11-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk_push', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
